### ISSUE TITLE
Пример отображени простой сцены на https://appleseedhq.net

### ISSUE THREAD

**Issue by zmm** [moevm/cv_dataset_generator#5]
Нужно сделать примитивное приложение, в котором на трехмерной сцене отображается несколько объектов + есть какое-то освещение. 

Пока - максимально просто, с хардкодом и прочим. Дальше мы будем развивать этот пример

**Comment by zmm** [comment]
альтернативы https://www.ogre3d.org/ , https://armory3d.org/

**Comment by ekiuled** [comment]
Я попыталась разобраться с рендерингом в отдельном окне c appleseed, в процессе оказалась в каких-то дебрях их кода, и быстрый пример сделать не удалось. Поэтому я решила посмотреть на OGRE из альтернатив, и там оказалась подробная вики с туториалами.

Я сделала пример сцены c двумя объектами и одним источником света, положила его в [папку ogre в ветке ogre ](https://github.com/moevm/cv_dataset_generator/tree/ogre/ogre). Вот что вышло:

![image](https://user-images.githubusercontent.com/31830048/110614925-e8c7e980-81a3-11eb-9be2-528010879ca1.png)

(Тени только почему-то с сильной лесенкой, хотя антиалиасинг вроде включен.)

**Comment by ekiuled** [comment]
Что-то я сначала не заметила, что у кубика углы ровные, и аласинг тут ни при чём. Это встроенная сфера была низкополигональная.

![Scene](https://user-images.githubusercontent.com/31830048/110929122-ae438580-8338-11eb-95db-4d1c5b4dabbc.png)
